- name: install dependencies
  tags: init
  shell: |
    apt-get update

- name: download and install rust
  tags: init
  shell: |
    wget -qO - https://sh.rustup.rs | RUSTUP_HOME=/opt/rust CARGO_HOME=/opt/rust sh -s -- --no-modify-path -y
