[package]
name = "public_ledger_for_auctions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-hash = "0.3.3"
hex = "0.3.2"
chrono = "0.4"
serde_json = "1.0"
sha2 = "0.10"
