[package]
name = "kademlia_node_search"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
tonic = "0.11.0"
prost = "0.12.3"
tokio = { version = "1.0", features = ["full"] }

[build-dependencies]
tonic-build = "0.11.0"